services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  hw1:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Homework1:/usr/local/apache2/htdocs

  hw2:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Homework2:/usr/local/apache2/htdocs
  hw3:
    build: ./Homework3
    restart: unless-stopped
    volumes:
    - ./Homework3/templates:/app/templates
    - ./Homework3/static:/app/static

  hw4:
    build: ./Homework4
    restart: unless-stopped
    volumes:
    - ./Homework4/static:/app/static
    - ./Homework4/templates:/app/templates
    - ./Homework4/src:/app/src
  
  hw5:
    build: ./Homework5
    restart: unless-stopped
    volumes:
    - ./Homework5/static:/app/static
    - ./Homework5/templates:/app/templates
    - ./Homework5/src:/app/src