services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
    env_file:
      - ./Project5/.env_sample

  p1:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Project1:/usr/local/apache2/htdocs

  p2:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Project2:/usr/local/apache2/htdocs
  p3:
    build: ./Project3
    restart: unless-stopped
    volumes:
    - ./Project3/templates:/app/templates
    - ./Project3/static:/app/static

  p4:
    build: ./Project4
    restart: unless-stopped
    volumes:
    - ./Project4/static:/app/static
    - ./Project4/templates:/app/templates
    - ./Project4/src:/app/src
  
  p5:
    build: ./Project5
    restart: unless-stopped
    volumes:
    - ./Project5/static:/app/static
    - ./Project5/templates:/app/templates
    - ./Project5/src:/app/src